#################################开发环境##########################
# --配置tomcat start
server:
  port: 8080
  tomcat:
    max-threads: 200
    max-connections: 1000
# --配置tomcat end

spring:
  # --druid 连接池配置 start
  datasource:
    url: jdbc:mysql://192.168.1.107:3306/funds_analysis?characterEncoding=utf8
    username: root
    password: 11112222
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 500
    # 配置获取连接等待超时的时间
      maxWait: 60000
  # --druid 配置 end


#  #redis配置
  redis:
    host: 192.168.1.107
    port: 6379
    password: 11112222
    pool:
      max-idle: 10
      min-idle: 5
      max-active: 8
      max-wait: 3000
      max-total: 30


# --日志管理 start
logging:
  level:
    root: info
    Funds.dao.: debug
  file: ./logs/FA-Ecm
# --日志管理 end